### PR TITLE
Fixing deleting layer issue

### PR DESCRIPTION
**Pull request by samely**
@Rub21 I fixed this https://github.com/JOSM/turnlanes-tagging/issues/56

### CODE REVIEW

**Comment by Klumbumbus** [comment]
Was this fix already released?

**Comment by samely** [comment]
@Klumbumbus yeah, just update the plugin.

**Comment by Klumbumbus** [comment]
I'm using version 1470950886 and the problem is still there.

**Comment by samely** [comment]
That's the last version. Have you tried uninstalling the plugin and then installing it again?
Maybe I misunderstood the problem. It's working in this way...

anim

**Comment by Klumbumbus** [comment]
I just reinstalled.
See the following screencast. The NPE appears when you click on the plugin button in the menu or in the toolbar.
npe

Thread: AWT-EventQueue-2 (47) of javawsApplicationThreadGroup
java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.turnlanestagging.TurnLanesEditorDialog.waySelected(TurnLanesEditorDialog.java:466)
    at org.openstreetmap.josm.plugins.turnlanestagging.TurnLanesEditorDialog.startEditSession(TurnLanesEditorDialog.java:157)
    at org.openstreetmap.josm.plugins.turnlanestagging.LaunchAction.launchEditor(LaunchAction.java:58)
    at org.openstreetmap.josm.plugins.turnlanestagging.LaunchAction.actionPerformed(LaunchAction.java:37)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
    at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by samely** [comment]
@Klumbumbus sorry for the delay. [It's fixed](https://github.com/JOSM/turnlanes-tagging/pull/65). I don't know how fast svn refreshed itself, but I think in an hour you can update the plugin. Thanks for your feedback.

**Comment by Klumbumbus** [comment]
Thanks, it works for me now.

> I don't know how fast svn refreshed itself

The plugin list is updated every 10 minutes as far as I know.

**Pull request merged**
