### PR TITLE
Correctly fill in empty lanes as "none"

### LINKED ISSUE #73: don't change none to ||
similar too #66 
way has 

    none|none|none|slight_right

open turnlanes-tagging

Plugin change without any interaction to 

    none|none||slight_right

For example here: https://www.openstreetmap.org/way/144131022

### PR DESCRIPTION
**Pull request by dobratzp**
Fix #73 

I too prefer to use "none" for unmarked lanes and I often find situations where I want to use ```left|none|none|right``` and this plugin was inserting ```left|none||right``` instead.  This patch fixes this issue.

### CODE REVIEW

**Comment by don-vip** [comment]
Hello, sorry for the delay, I was not looking at this repository. Can you please update your PR? Some conflicts must be resolved.

**Comment by dobratzp** [comment]
Yeah, there have been a few changes since I made this patch a year ago.  If you agree with the general methodology I can take another look at this and resolve the conflicts sometime this week.

**Comment by don-vip** [comment]
The methodology is ok and it's a pleasure to see you have added unit tests!

**Comment by dobratzp** [comment]
Ok, I've attempted to merge the latest from JOSM/master to my fork.

**Comment by don-vip** [comment]
Thanks!

**Pull request merged**
